spring.application.name=auth-service

# Usuario simulado unicamente para desarrollo
aoo.demo-user.email = doctor@hospital.test
# si existe la variable de entorno, utiliza su valor, sino, utiliza hospital123!
app.demo-user.password = ${DEMO_USER_PASSWORD:Hospital123!}